### ISSUE TITLE
Pocket problem(s)

### ISSUE THREAD

**Issue by phil-barrett** [swarfer/sketchucam#6]
I have a relatively simple rectangle (made up 8 segments that when I pocket it, the normal pocket path gets drawn and then a 4200+ mm path gets added well outside the rectangle and safe area.  

In addition, if you generate gcode from this mutant pocket, it generates gcode outside the safe area. 

I tried constructing a similar rectangle with 8 segments but it doesn't demonstrate the problem.

SketchUcam V1.4d-80c0152 (which I believe is the latest)

[pocket bug.zip](https://github.com/swarfer/sketchucam/files/3507537/pocket.bug.zip)

**Comment by swarfer** [comment]
Hi
this is interesting.   That rectangle is not parallel to the Y axis, AND the sides of the rectangle are not parallel either.   If that is your intent then ok, but I suggest redrawing it with the rectangle tool.
(or at least selecting the outline and then using the 'repair bl and flatten' tool to reduce the line count)

When I pocket it in 1.4d I see that spurious line.  This is caused by the pocket routine trying to put a zigzag into the pocket. There is really no space but because of Sketchup's weird way of dealing with comparing numbers we get this strange line.    

The instant solution is to hold down CTRL when adding the pocket.   This will add only the outline which is sufficient to clear this narrow pocket.

Oddly I don't see this weird behavior with the upcoming V1.5 though I cannot recall changing anything in the pocket code.  I will have to compare the code carefully to track this down.

Hope this helps you.

**Comment by phil-barrett** [comment]
Thanks for looking at it. My solution (well before submitting the bug) was to redraw it with the rect tool. Not sure how it wound up with non-parallel lines in the first place - it started out a rectangle that I copied and extended to make a dado.  SKU sometimes can do some very odd things so I'm not surprised.
